# Generated by Django 3.2.13 on 2022-05-17 15:03

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=150, verbose_name='Наименование бренда')),
                ('description', models.TextField(max_length=140)),
                ('image', models.ImageField(blank=True, upload_to='brand/', verbose_name='Логотип')),
            ],
            options={
                'verbose_name': 'бренд',
                'verbose_name_plural': 'бренды',
                'ordering': ('title',),
            },
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=20, verbose_name='Наименование склада')),
            ],
            options={
                'verbose_name': 'склад',
                'verbose_name_plural': 'склады',
                'ordering': ('title',),
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=150, verbose_name='Название товарв')),
                ('dimension', models.CharField(max_length=10, verbose_name='Единица измерения')),
                ('description', models.TextField(max_length=140)),
                ('media_content', models.FileField(blank=True, upload_to='product/', verbose_name='Медиа контент')),
                ('retail_price', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('wholesale_price', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('date_of_receipt', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата поступления')),
                ('date_of_liquidation', models.DateTimeField(blank=True, null=True, verbose_name='Дата ликвидации')),
                ('quantity', models.DecimalField(decimal_places=1, max_digits=6, validators=[django.core.validators.MinValueValidator(1)])),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.brand')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.store')),
            ],
            options={
                'verbose_name': 'товар',
                'verbose_name_plural': 'товары',
                'ordering': ('-date_of_receipt',),
            },
        ),
        migrations.CreateModel(
            name='BrandsStore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brands', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.brand')),
                ('stores', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.store')),
            ],
        ),
        migrations.AddField(
            model_name='brand',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.store'),
        ),
        migrations.AddConstraint(
            model_name='brandsstore',
            constraint=models.UniqueConstraint(fields=('brands', 'stores'), name='unique_stores_brand'),
        ),
    ]
