# Generated by Django 3.2.13 on 2022-05-17 10:41

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=150, verbose_name='Наименование бренда')),
                ('description', models.TextField(max_length=140)),
                ('image', models.ImageField(upload_to='brand/', verbose_name='Логотип')),
            ],
            options={
                'verbose_name': 'бренд',
                'verbose_name_plural': 'брендов',
                'ordering': ('title',),
            },
        ),
        migrations.CreateModel(
            name='BrandProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_brand', to='product.brand')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=150, verbose_name='Название товарв')),
                ('dimension', models.CharField(max_length=10, verbose_name='Единица измерения')),
                ('description', models.TextField(max_length=140)),
                ('media_content', models.FileField(upload_to='product/', verbose_name='Медиа контент')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('date_of_receipt', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата поступления')),
                ('date_of_liquidation', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата ликвидации')),
                ('brand', models.ManyToManyField(through='product.BrandProduct', to='product.Brand')),
            ],
            options={
                'verbose_name': 'товар',
                'verbose_name_plural': 'товары',
                'ordering': ('-date_of_receipt', '-date_of_liquidation'),
            },
        ),
        migrations.AddField(
            model_name='brandproduct',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product'),
        ),
        migrations.AddConstraint(
            model_name='brandproduct',
            constraint=models.UniqueConstraint(fields=('product', 'brand'), name='unique_brand_product'),
        ),
    ]
