# Generated by Django 3.2.13 on 2022-05-17 11:23

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brand',
            options={'ordering': ('title',), 'verbose_name': 'бренд', 'verbose_name_plural': 'бренды'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('-date_of_receipt',), 'verbose_name': 'товар', 'verbose_name_plural': 'товары'},
        ),
        migrations.RenameField(
            model_name='product',
            old_name='price',
            new_name='ritail_price',
        ),
        migrations.AddField(
            model_name='product',
            name='wholesale_price',
            field=models.DecimalField(decimal_places=2, default=1705, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='date_of_liquidation',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата ликвидации'),
        ),
        migrations.AlterField(
            model_name='product',
            name='media_content',
            field=models.FileField(blank=True, upload_to='product/', verbose_name='Медиа контент'),
        ),
    ]
